version: "3.5"

volumes:
  clutch_postgres_data: {}

services:
  database:
    image: postgres:9.6.3
    ports:
      - "5432:5432"
    volumes:
      - clutch_postgres_data:/var/lib/postgresql/data
  splash:
    image: scrapinghub/splash:latest
    ports:
      - "8050:8050"
    depends_on:
      - database
