---
- name: Set up nginx config
  apt: name=nginx state=latest
  become: yes

- name: Write nginx conf file
  template: src=nginx.j2 dest=/etc/nginx/conf.d/{{ app_name }}.conf
  become: yes
  notify:
    - restart nginx

- name: Disable the default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: yes
  notify:
    - restart nginx
