---
# dev & stage case, postgres installed at the same server as runs app
- name: Install and configure db
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
  when: db_setup

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes
  when: db_setup

- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres
  become: yes
  when: db_setup

- name: Configure a new postgresql user
  postgresql_user: db={{ db_name }}
                    name={{ db_user }}
                    password={{ db_user_password }}
                    priv=ALL
                    encrypted=yes
  become: yes
  become_user: postgres
  when: db_setup
