---
- name: Add docker keys
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Install required packages
  apt: name={{item}} state=latest update_cache=yes
  become: yes
  with_items:
    - gcc
    - vim
    - virtualenv
    - python3
    - python3.6-dev
    - python2.7-dev
    - libpq-dev
    - python3-psycopg2
    - uwsgi-plugin-python3
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce

- name: Ensure a locale exists
  locale_gen: name=en_US.UTF-8 state=present

